/**
 * Route table — GENERATED by scripts/codemod-routes.mjs from the old Next.js
 * `app/` tree. Edit the handlers under server/routes/, and add new routes here
 * by hand; this file is no longer regenerated.
 *
 * Paths use `:param` segments. Static segments beat dynamic ones at the same
 * position (see server/router.ts), which is what preserves Next's behaviour of
 * a literal directory shadowing a `[param]` one — e.g. /api/v1/orders/preview
 * must win over /api/v1/orders/:id.
 */

import { Router, type Handler } from './router';
import * as _well_known_oauth_authorization_server from './routes/well-known.oauth-authorization-server';
import * as _well_known_oauth_protected_resource from './routes/well-known.oauth-protected-resource';
import * as api_health from './routes/api.health';
import * as api_ui_account from './routes/api.ui.account';
import * as api_ui_creds__mode from './routes/api.ui.creds.$mode';
import * as api_ui_events from './routes/api.ui.events';
import * as api_ui_keys__id from './routes/api.ui.keys.$id';
import * as api_ui_keys from './routes/api.ui.keys';
import * as api_ui_lookup_currencies from './routes/api.ui.lookup.currencies';
import * as api_ui_lookup_instruments from './routes/api.ui.lookup.instruments';
import * as api_ui_lookup_markets from './routes/api.ui.lookup.markets';
import * as api_ui_me from './routes/api.ui.me';
import * as api_ui_oauth_consent from './routes/api.ui.oauth.consent';
import * as api_ui_oauth_context from './routes/api.ui.oauth.context';
import * as api_ui_sessions from './routes/api.ui.sessions';
import * as api_ui_telegram_bot from './routes/api.ui.telegram.bot';
import * as api_ui_telegram_link_code from './routes/api.ui.telegram.link-code';
import * as api_ui_telegram from './routes/api.ui.telegram';
import * as api_v1_cash from './routes/api.v1.cash';
import * as api_v1_considered from './routes/api.v1.considered';
import * as api_v1_fills from './routes/api.v1.fills';
import * as api_v1_holdings from './routes/api.v1.holdings';
import * as api_v1_instruments__symbol from './routes/api.v1.instruments.$symbol';
import * as api_v1_journal from './routes/api.v1.journal';
import * as api_v1_markets from './routes/api.v1.markets';
import * as api_v1_orders__id from './routes/api.v1.orders.$id';
import * as api_v1_orders_preview from './routes/api.v1.orders.preview';
import * as api_v1_orders from './routes/api.v1.orders';
import * as api_v1_session_refresh from './routes/api.v1.session.refresh';
import * as api_v1_snapshots__date from './routes/api.v1.snapshots.$date';
import * as api_v1_snapshots from './routes/api.v1.snapshots';
import * as api_v1_state_portfolio from './routes/api.v1.state.portfolio';
import * as api_v1_telegram_webhook__secret from './routes/api.v1.telegram.webhook.$secret';
import * as mcp from './routes/mcp';
import * as oauth_register from './routes/oauth.register';
import * as oauth_revoke from './routes/oauth.revoke';
import * as oauth_token from './routes/oauth.token';

export function buildRouter(): Router {
  const r = new Router();
  r.add('GET', '/.well-known/oauth-authorization-server', _well_known_oauth_authorization_server.GET as Handler);
  r.add('GET', '/.well-known/oauth-protected-resource', _well_known_oauth_protected_resource.GET as Handler);
  r.add('GET', '/api/health', api_health.GET as Handler);
  r.add('GET', '/api/ui/account', api_ui_account.GET as Handler);
  r.add('GET', '/api/ui/creds/:mode', api_ui_creds__mode.GET as Handler);
  r.add('PUT', '/api/ui/creds/:mode', api_ui_creds__mode.PUT as Handler);
  r.add('DELETE', '/api/ui/creds/:mode', api_ui_creds__mode.DELETE as Handler);
  r.add('GET', '/api/ui/events', api_ui_events.GET as Handler);
  r.add('PATCH', '/api/ui/keys/:id', api_ui_keys__id.PATCH as Handler);
  r.add('DELETE', '/api/ui/keys/:id', api_ui_keys__id.DELETE as Handler);
  r.add('GET', '/api/ui/keys', api_ui_keys.GET as Handler);
  r.add('POST', '/api/ui/keys', api_ui_keys.POST as Handler);
  r.add('GET', '/api/ui/lookup/currencies', api_ui_lookup_currencies.GET as Handler);
  r.add('GET', '/api/ui/lookup/instruments', api_ui_lookup_instruments.GET as Handler);
  r.add('GET', '/api/ui/lookup/markets', api_ui_lookup_markets.GET as Handler);
  r.add('GET', '/api/ui/me', api_ui_me.GET as Handler);
  r.add('POST', '/api/ui/me', api_ui_me.POST as Handler);
  r.add('POST', '/api/ui/oauth/consent', api_ui_oauth_consent.POST as Handler);
  r.add('GET', '/api/ui/oauth/context', api_ui_oauth_context.GET as Handler);
  r.add('GET', '/api/ui/sessions', api_ui_sessions.GET as Handler);
  r.add('GET', '/api/ui/telegram/bot', api_ui_telegram_bot.GET as Handler);
  r.add('PUT', '/api/ui/telegram/bot', api_ui_telegram_bot.PUT as Handler);
  r.add('DELETE', '/api/ui/telegram/bot', api_ui_telegram_bot.DELETE as Handler);
  r.add('POST', '/api/ui/telegram/link-code', api_ui_telegram_link_code.POST as Handler);
  r.add('GET', '/api/ui/telegram', api_ui_telegram.GET as Handler);
  r.add('DELETE', '/api/ui/telegram', api_ui_telegram.DELETE as Handler);
  r.add('GET', '/api/v1/cash', api_v1_cash.GET as Handler);
  r.add('GET', '/api/v1/considered', api_v1_considered.GET as Handler);
  r.add('POST', '/api/v1/considered', api_v1_considered.POST as Handler);
  r.add('GET', '/api/v1/fills', api_v1_fills.GET as Handler);
  r.add('POST', '/api/v1/fills', api_v1_fills.POST as Handler);
  r.add('GET', '/api/v1/holdings', api_v1_holdings.GET as Handler);
  r.add('GET', '/api/v1/instruments/:symbol', api_v1_instruments__symbol.GET as Handler);
  r.add('GET', '/api/v1/journal', api_v1_journal.GET as Handler);
  r.add('POST', '/api/v1/journal', api_v1_journal.POST as Handler);
  r.add('GET', '/api/v1/markets', api_v1_markets.GET as Handler);
  r.add('GET', '/api/v1/orders/:id', api_v1_orders__id.GET as Handler);
  r.add('POST', '/api/v1/orders/preview', api_v1_orders_preview.POST as Handler);
  r.add('GET', '/api/v1/orders', api_v1_orders.GET as Handler);
  r.add('POST', '/api/v1/orders', api_v1_orders.POST as Handler);
  r.add('POST', '/api/v1/session/refresh', api_v1_session_refresh.POST as Handler);
  r.add('GET', '/api/v1/snapshots/:date', api_v1_snapshots__date.GET as Handler);
  r.add('PUT', '/api/v1/snapshots/:date', api_v1_snapshots__date.PUT as Handler);
  r.add('GET', '/api/v1/snapshots', api_v1_snapshots.GET as Handler);
  r.add('GET', '/api/v1/state/portfolio', api_v1_state_portfolio.GET as Handler);
  r.add('PUT', '/api/v1/state/portfolio', api_v1_state_portfolio.PUT as Handler);
  r.add('POST', '/api/v1/telegram/webhook/:secret', api_v1_telegram_webhook__secret.POST as Handler);
  r.add('GET', '/mcp', mcp.GET as Handler);
  r.add('POST', '/mcp', mcp.POST as Handler);
  r.add('POST', '/oauth/register', oauth_register.POST as Handler);
  r.add('POST', '/oauth/revoke', oauth_revoke.POST as Handler);
  r.add('POST', '/oauth/token', oauth_token.POST as Handler);
  return r;
}
