#!/usr/bin/env node
/**
 * One-shot codemod: move the Next.js route handlers under `app/` into
 * `server/routes/`, strip the Next-isms, and generate the route registry.
 *
 * This exists because the handlers were already written against a wrapper
 * (`withRoute`) whose contract did not change when Next.js came out — so the
 * bodies port mechanically and the risky part is only the mapping from Next's
 * file-system routing to an explicit table. Doing that by hand across 37 files
 * is where a typo'd path would hide; generating it means the table is derived
 * from the same tree Next was reading.
 *
 * Run once, then delete. Not part of the build.
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const SRC = path.join(ROOT, 'app');
const DEST = path.join(ROOT, 'server', 'routes');

/** Every route.ts under app/, as { file, urlPath }. */
function findRoutes(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) findRoutes(p, out);
    else if (e.name === 'route.ts') out.push(p);
  }
  return out;
}

/** app/api/v1/orders/[id]/route.ts -> /api/v1/orders/:id */
function urlPathOf(file) {
  const rel = path.relative(SRC, path.dirname(file));
  const segs = rel.split(path.sep).filter(Boolean).map((s) =>
    s.startsWith('[') && s.endsWith(']') ? ':' + s.slice(1, -1) : s,
  );
  return '/' + segs.join('/');
}

/** Destination module path, flattened and stable: /api/v1/orders/:id -> api.v1.orders.$id */
function moduleNameOf(urlPath) {
  return urlPath
    .split('/')
    .filter(Boolean)
    .map((s) => (s.startsWith(':') ? '$' + s.slice(1) : s))
    .join('.')
    .replace(/[^A-Za-z0-9.$_-]/g, '_');
}

function transform(src) {
  let s = src;
  // Next route-segment config has no meaning outside Next.
  s = s.replace(/^export const (runtime|dynamic|revalidate|fetchCache) = .*;\n/gm, '');
  // NextRequest is structurally a Request for everything these handlers use.
  s = s.replace(/\bNextRequest\b/g, 'Request');
  // NextResponse.json(...) -> json(...) from our own helper.
  s = s.replace(/\bNextResponse\.json\(/g, 'json(');
  // `new NextResponse(...)` / `NextResponse(...)` -> plain Response.
  s = s.replace(/\bnew NextResponse\(/g, 'new Response(');
  s = s.replace(/\bNextResponse\.redirect\(/g, 'Response.redirect(');
  // nextUrl is just the parsed URL.
  s = s.replace(/\breq\.nextUrl\b/g, 'new URL(req.url)');
  s = s.replace(/\brequest\.nextUrl\b/g, 'new URL(request.url)');
  // Drop the next/server import; add `json` if the file now needs it.
  const needsJson = /\bjson\(/.test(s);
  s = s.replace(/^import \{[^}]*\} from 'next\/server';\n/gm, '');
  s = s.replace(/^import type \{[^}]*\} from 'next\/server';\n/gm, '');
  if (needsJson && !/from '@\/lib\/errors'/.test(s)) {
    s = s.replace(/^(\/\*[\s\S]*?\*\/\n\n?)?/, (m) => m + "import { json } from '@/lib/errors';\n");
  } else if (needsJson) {
    // errors is already imported — make sure `json` is in the named list.
    s = s.replace(/import \{([^}]*)\} from '@\/lib\/errors';/, (m, names) =>
      names.includes('json') ? m : `import {${names.trimEnd()}, json } from '@/lib/errors';`,
    );
  }
  return s;
}

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];

const routes = findRoutes(SRC).sort();
fs.mkdirSync(DEST, { recursive: true });

const registry = [];
for (const file of routes) {
  const urlPath = urlPathOf(file);
  const modName = moduleNameOf(urlPath);
  const src = fs.readFileSync(file, 'utf8');
  const out = transform(src);
  const methods = HTTP_METHODS.filter((m) =>
    new RegExp(`export const ${m}\\b|export async function ${m}\\b|export function ${m}\\b`).test(out),
  );
  if (!methods.length) {
    console.warn(`  !! ${urlPath}: no exported HTTP methods found — skipped`);
    continue;
  }
  fs.writeFileSync(path.join(DEST, `${modName}.ts`), out);
  registry.push({ urlPath, modName, methods });
  console.log(`  ${urlPath.padEnd(46)} ${methods.join(',')}`);
}

// ---- registry -------------------------------------------------------------

const imports = registry
  .map((r) => `import * as ${r.modName.replace(/[.$-]/g, '_')} from './routes/${r.modName}';`)
  .join('\n');

const adds = registry
  .flatMap((r) =>
    r.methods.map(
      (m) =>
        `  r.add('${m}', '${r.urlPath}', ${r.modName.replace(/[.$-]/g, '_')}.${m} as Handler);`,
    ),
  )
  .join('\n');

fs.writeFileSync(
  path.join(ROOT, 'server', 'registry.ts'),
  `/**
 * Route table — GENERATED by scripts/codemod-routes.mjs from the old Next.js
 * \`app/\` tree. Edit the handlers under server/routes/, and add new routes here
 * by hand; this file is no longer regenerated.
 *
 * Paths use \`:param\` segments. Static segments beat dynamic ones at the same
 * position (see server/router.ts), which is what preserves Next's behaviour of
 * a literal directory shadowing a \`[param]\` one — e.g. /api/v1/orders/preview
 * must win over /api/v1/orders/:id.
 */

import { Router, type Handler } from './router';
${imports}

export function buildRouter(): Router {
  const r = new Router();
${adds}
  return r;
}
`,
);

console.log(`\n${registry.length} route modules -> server/routes/, registry -> server/registry.ts`);
